version: '3'
services:
  backend:
    image: armza/shop-backend-node
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=27017
      - DB_NAME=my_app
      - JWT_KEY=1JFAi4s5D5L4MYkUgfDHyenLKgnum73d

  frontend:
    image: armza/shop-frontend-vue
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    depends_on:
      - backend